name: Nightly Docker Image Rebuild
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push devel
        uses: docker/build-push-action@v3
        with:
          context: docker/devel/
          push: true
          tags: sivel/ansible-template-ui:latest

      - name: Build and push stable
        uses: docker/build-push-action@v3
        with:
          context: docker/stable/
          push: true
          tags: sivel/ansible-template-ui:stable
